language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5

install:
  - sudo apt-get update -qq
  - sudo apt-get install libpcap-dev -qq
  - bundle install --path vendor/bundle --jobs=3 --retry=3
script:
  - bundle exec rake
