language: ruby
rvm:
  - 2.3
  - 2.4
  - 2.5

install:
  - sudo apt-get update -qq
  - sudo apt-get install libpcap-dev -qq
  - gem install bundler --version "~>1.17.3"
  - bundle install --path vendor/bundle --jobs=3 --retry=3
  